# Generated by Django 5.0.1 on 2025-11-05 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, help_text='Console MAC address (e.g., 00:09:bf:11:22:33)', max_length=17, unique=True)),
                ('user_id', models.CharField(db_index=True, help_text='Nintendo User ID', max_length=50)),
                ('device_name', models.CharField(blank=True, help_text='Console nickname', max_length=100)),
                ('platform', models.CharField(choices=[('DS', 'Nintendo DS'), ('DSi', 'Nintendo DSi'), ('Wii', 'Nintendo Wii')], default='DS', max_length=10)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this console can connect')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Console',
                'verbose_name_plural': 'Consoles',
                'db_table': 'consoles',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='NASLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=50)),
                ('auth_token', models.CharField(max_length=255, unique=True)),
                ('data', models.JSONField(help_text='Complete NAS login data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'NAS Login',
                'verbose_name_plural': 'NAS Logins',
                'db_table': 'nas_logins',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('active_consoles', models.IntegerField(default=0)),
                ('active_profiles', models.IntegerField(default=0)),
                ('active_servers', models.IntegerField(default=0)),
                ('total_logins_today', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Server Statistic',
                'verbose_name_plural': 'Server Statistics',
                'db_table': 'server_statistics',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='BannedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_type', models.CharField(choices=[('ip', 'IP Address'), ('mac', 'MAC Address'), ('profile', 'Profile ID'), ('userid', 'User ID')], max_length=10)),
                ('identifier', models.CharField(db_index=True, help_text='The banned identifier (IP, MAC, etc.)', max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for permanent ban', null=True)),
                ('banned_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Banned Item',
                'verbose_name_plural': 'Banned Items',
                'db_table': 'banned',
                'ordering': ['-banned_at'],
                'unique_together': {('ban_type', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text='Nintendo User ID', max_length=50)),
                ('game_id', models.CharField(db_index=True, help_text='Game ID (e.g., ADAJ for Pokemon Diamond)', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gs_broadcast_code', models.CharField(blank=True, max_length=50)),
                ('uniquenick', models.CharField(blank=True, max_length=50)),
                ('console', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='dwc_admin.console')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profiles',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'game_id')},
            },
        ),
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=50, unique=True)),
                ('game_name', models.CharField(db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('max_players', models.IntegerField(default=4)),
                ('current_players', models.IntegerField(default=0)),
                ('game_data', models.JSONField(default=dict, help_text='Additional game-specific data')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('host_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_servers', to='dwc_admin.profile')),
            ],
            options={
                'verbose_name': 'Game Server',
                'verbose_name_plural': 'Game Servers',
                'db_table': 'game_servers',
                'ordering': ['-last_heartbeat'],
            },
        ),
    ]
