# Generated by Django 5.0.1 on 2025-11-19 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwc_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowList',
            fields=[
                ('user_id', models.IntegerField(help_text='User ID (console owner)', primary_key=True, serialize=False)),
                ('mac_address', models.CharField(db_column='macadr', db_index=True, help_text='Console MAC address', max_length=17)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this whitelist entry is active')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
            ],
            options={
                'verbose_name': 'Whitelist Entry',
                'verbose_name_plural': 'Whitelist (Allow List)',
                'db_table': 'allow_list',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='NatNeg',
            fields=[
                ('cookie', models.BigIntegerField(help_text='NAT negotiation cookie', primary_key=True, serialize=False)),
                ('client_addr', models.GenericIPAddressField(db_column='clientaddr', help_text='Client IP address')),
                ('client_port', models.IntegerField(db_column='clientport', help_text='Client port')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NAT Negotiation',
                'verbose_name_plural': 'NAT Negotiations',
                'db_table': 'natneg',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='aim',
            field=models.CharField(blank=True, help_text='AIM username', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.CharField(blank=True, help_text='Birthdate', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='bssid',
            field=models.CharField(blank=True, help_text='Router MAC address', max_length=17),
        ),
        migrations.AddField(
            model_name='profile',
            name='cfc',
            field=models.CharField(blank=True, help_text='Cached Friend Code', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='csnum',
            field=models.CharField(blank=True, help_text='Console Serial Number', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='devname',
            field=models.CharField(blank=True, help_text='Device name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, help_text='Latitude', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loc',
            field=models.CharField(blank=True, help_text='Location string', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(blank=True, help_text='Longitude', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='partnerid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, help_text='GameSpy password hash', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='pid',
            field=models.CharField(blank=True, help_text='Player ID', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='stat',
            field=models.TextField(blank=True, help_text='User statistics'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='host_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_servers', to='dwc_admin.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gs_broadcast_code',
            field=models.CharField(blank=True, db_column='gsbrcd', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uniquenick',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DenyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, help_text='User ID to ban')),
                ('game_id', models.CharField(db_column='gameid', db_index=True, help_text='Game ID (e.g., ADAJ for Pokemon Diamond)', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for ban')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.CharField(blank=True, help_text='Admin who issued ban', max_length=50)),
            ],
            options={
                'verbose_name': 'Game Ban',
                'verbose_name_plural': 'Deny List (Game Bans)',
                'db_table': 'deny_list',
                'ordering': ['-banned_at'],
                'unique_together': {('user_id', 'game_id')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_key', models.CharField(help_text='GameSpy session key', max_length=255, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField(auto_now_add=True, db_column='logintime', help_text='When the session was created')),
                ('profile', models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dwc_admin.profile')),
            ],
            options={
                'verbose_name': 'GP Session',
                'verbose_name_plural': 'GP Sessions',
                'db_table': 'sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(db_column='groupid', help_text='Matchmaking group identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(db_column='profileid', on_delete=django.db.models.deletion.CASCADE, related_name='pending_matches', to='dwc_admin.profile')),
            ],
            options={
                'verbose_name': 'Pending Match',
                'verbose_name_plural': 'Pending Matches',
                'db_table': 'pending',
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'group_id')},
            },
        ),
    ]
